name: Deploy Backend to Render

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # 🔥 FIX: Inyectamos una URL falsa para engañar a Prisma durante la compilación
    env:
      DATABASE_URL: "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias limpias
        run: npm ci

      - name: Verificar compilación de NestJS
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al Webhook de Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}